let dados = [
  {
    nome: "Bugia (Melipona Rufiventris)",
    descricao: "A Bugia, cientificamente conhecida como Melipona rufiventris, é uma das abelhas sem ferrão mais famosas e valorizadas do Brasil. Conhecida por sua produção de mel de alta qualidade e sabor único, a Bugia é um tesouro da Mata Atlântica, abelha de grande porte, com coloração amarelo-ouro e faixas pretas no abdômen. É uma espécie rústica e produtiva, sendo bastante apreciada pelos meliponicultores.",
    ocorrencia: "Mata Atlântica",
    Tamanho: "De porte grande, sendo uma das maiores abelhas sem ferrão do Brasil, com cerca de 11 a 13 mm de comprimento.",
    Coloração: "Predominantemente amarela, com pelos ferrugíneos que recobrem todo o corpo, conferindo-lhe um aspecto aveludado.",
    tags: "Mata Atlântica Meliponini Abelha sem ferrão",
    link: "https://pt.wikipedia.org/wiki/Melipona_rufiventris",
    imagem: "https://abelhas.org:9443/MediaUploader/e722df0f26eb45868821be200e116f2b.jpg",
  },
  {
    nome: "Jataí (Tetragonisca Angustula)",
    descricao: "A Jataí, cientificamente conhecida como Tetragonisca angustula, é uma das abelhas sem ferrão mais populares e apreciadas no Brasil. Pequena em tamanho, mas grande em importância, a Jataí é conhecida por sua docilidade e produção de mel de alta qualidade.",
    ocorrencia: "Ampla distribuição no Brasil",
    Tamanho: "Uma das menores abelhas sem ferrão, com cerca de 4 a 5 mm de comprimento.",
    Coloração: "Amarelo-ouro brilhante, com corbículas (cestos de pólen) pretas.",
    Ninhos: "Constroem seus ninhos em cavidades de árvores, cupinzeiros ou em caixas racionais.",
    Produção: "Produzem mel de sabor suave, levemente azedinho e com aroma floral, muito apreciado pelos consumidores. Além do mel, produzem própolis e geleia real.",
    tags: "Brasil Pequeno Amarelo-ouro Dócil Mel Própolis",
    link: "https://pt.wikipedia.org/wiki/Tetragonisca_angustula",
    imagem: "https://ecoa.org.br/wp-content/uploads/2022/04/abelha_jatai_1_fixed_large.jpg",
  },
  {
    nome: "Uruçu Nordestina (Melipona scutellaris",
    descricao: "A Uruçu Nordestina, cientificamente conhecida como Melipona scutellaris, é uma das abelhas sem ferrão mais famosas e valorizadas do Brasil. Conhecida por sua produção de mel de alta qualidade e sabor único, a Uruçu Nordestina é um símbolo da biodiversidade do Nordeste.",
    ocorrencia: "Nordeste do Brasil",
    Tamanho: "De porte grande, sendo uma das maiores abelhas sem ferrão do Brasil, com cerca de 10 a 12 mm de comprimento.",
    Coloração: "Predominantemente negra, com algumas variações de tonalidade e pelos amarelados.",
    tags: "Nordeste Grande Escuro Amarelo Mel Meliponini",
    link: "https://pt.wikipedia.org/wiki/Uru%C3%A7u",
    imagem: "https://exemplo.com/imagem_urucu.jpg",
  },
  {
    nome: "Tiúba (Melipona compressipes)",
    descricao: "A Tiúba, cientificamente conhecida como Melipona compressipes, também chamada de Uruçu-cinzenta, é uma espécie de abelha sem ferrão largamente criada no norte dos estados do Pará, Maranhão e Piauí. Conhecida por sua produção de mel de alta qualidade e sabor único, a Tiúba é um símbolo da biodiversidade da região amazônica.",
    ocorrencia: "Ampla distribuição no Brasil",
    Tamanho: "De porte médio, com cerca de 8 a 10 mm de comprimento.",
    Coloração: "Predominantemente negra, com pelos cinzentos que recobrem o tórax e o abdômen, conferindo-lhe um aspecto aveludado.",
    Ninhos: "Constroem seus ninhos em cavidades de árvores, cupinzeiros ou em caixas racionais.",
    Produção: "Produzem mel de sabor forte e levemente ácido, com notas florais e frutadas. Além do mel, produzem própolis e geleia real.",
    tags: "Brasil Médio Escuro Amarelo Rústica Meliponini Adaptabilidade",
    link: "https://exemplo.com/tiuba",
    imagem: "https://exemplo.com/imagem_tiuba.jpg",
  },
  {
    nome: "jandaira (Melipona subnitida)",
    descricao: "A Jandaíra, cientificamente conhecida como Melipona subnitida, é uma espécie de abelha sem ferrão endêmica do Nordeste brasileiro. Conhecida por sua produção de mel de alta qualidade e sabor único, a Jandaíra é um símbolo da biodiversidade da região.",
    ocorrencia: "Nordeste do Brasil",
    Tamanho: "De porte médio, com cerca de 6 a 7 mm de comprimento.",
    Coloração: "Predominantemente negra, com algumas variações de tonalidade e pelos amarelados.",
    Ninhos: "Constroem seus ninhos em cavidades de árvores, cupinzeiros ou em caixas racionais.",
    Produção: "Produzem mel de sabor levemente ácido, com notas florais e frutadas. Além do mel, produzem própolis e geleia real.", 
    tags: "Nordeste Médio Escuro Amarelo Mel Meliponini",
    link: "https://pt.wikipedia.org/wiki/Melipona_subnitida",
    imagem: "https://abelhas.org:9443/MediaUploader/03c65401681d40afb04688c688e19d56.jpeg",
  },
  {
    nome: "Iraí (Scaptotrigona postica)",
    descricao: "A Iraí, cientificamente conhecida como Exodonta masaru, é uma espécie de abelha sem ferrão endêmica da Mata Atlântica, especialmente encontrada em regiões de altitude. Conhecida por sua produção de mel de alta qualidade e sabor único, a Iraí é uma espécie muito valorizada pelos meliponicultores.",
    ocorrencia: "Ampla distribuição no Brasil",
    Tamanho: "De porte médio, com cerca de 6 a 7 mm de comprimento.",
    Coloração: "Predominantemente negra, com algumas variações de tonalidade e pelos amarelados.",
    Ninhos: "Constroem seus ninhos em cavidades de árvores, cupinzeiros ou em caixas racionais.",
    Produção: "Produzem mel de sabor forte e levemente ácido, com notas florais e frutadas. Além do mel, produzem própolis e geleia real.",
    tags: "Brasil Pequeno Escuro Brilhante Mel Cavidades Scaptotrigona",
    link: "https://pt.wikipedia.org/wiki/Ira%C3%AD",
    imagem: "https://www.iguiecologia.com/abelha-nativa-brasileira-irai-nannotrigona-testaceicora/",
  },
  {
    nome: "Mandaçaia (Melipona quadrifasciata)",
    descricao: "A Mandaçaia, cientificamente conhecida como Melipona quadrifasciata, é uma das abelhas sem ferrão mais populares e valorizadas no Brasil. Conhecida por sua produção de mel de alta qualidade e sabor único, a Mandaçaia é uma espécie emblemática da meliponicultura brasileira.",
    ocorrencia: "Região Sul, especialmente Santa Catarina",
    Tamanho: "De porte médio, com cerca de 6 a 7 mm de comprimento.",
    Coloração: "Predominantemente negra, com faixas amarelas no abdômen, que variam em número e espessura dependendo da subespécie.",
    Ninhos: "Constroem seus ninhos em cavidades de árvores, cupinzeiros ou em caixas racionais.",
    Produção: "Produzem mel de sabor forte e levemente ácido, muito apreciado pelos consumidores. Além do mel, produzem própolis e geleia real.",
    tags: "Médio porte Mel de alta qualidade Meliponini",
    link: "https://pt.wikipedia.org/wiki/Melipona_quadrifasciata",
    imagem: "https://www.sedest.pr.gov.br/sites/default/arquivos_restritos/files/imagem/2022-03/mandacaia_1.jpg",
  },
  {
    nome: "Guaraipo (Melipona bicolor schencki )",
    descricao: "A Guaraipo, cientificamente conhecida como Melipona bicolor schencki, é uma espécie de abelha sem ferrão bastante apreciada pelos meliponicultores. Conhecida por sua docilidade e produção de mel de alta qualidade, a Guaraipo é uma das espécies mais populares para a criação em meliponários.",
    ocorrencia: "Região Sul",
    Tamanho: "De porte médio, com cerca de 6 a 7 mm de comprimento.",
    Coloração: "Predominantemente negra, com algumas variações de tonalidade e pelos amarelados.",
    Ninhos: "Constroem seus ninhos em cavidades de árvores, cupinzeiros ou em caixas racionais.",
    Produção: "Produzem mel de sabor suave e levemente azedinho, muito apreciado pelos consumidores. Além do mel, produzem própolis e geleia real.",
    tags: "Agressiva Mel Meliponini",
    link: "https://pt.wikipedia.org/wiki/Melipona_bicolor",
    imagem: "https://exemplo.com/imagem_guaraipo.jpg",
  },
  {
    nome: "Manduri (Melipona obscurior)",
    descricao: "A abelha Manduri, cientificamente conhecida como Melipona obscurior, é uma espécie de abelha sem ferrão bastante interessante e valorizada pelos meliponicultores. Diversas variedades, características específicas por região.",
    ocorrencia: "Santa Catarina",
    Tamanho: "De porte médio, com cerca de 6 a 7 mm de comprimento",
    Coloração: "Predominantemente negra, com faixas amarelas onduladas no abdômen",
    Ninhos: "Constroem seus ninhos em ocos de árvores ou em paredões de taipa, mas adaptam-se bem a caixas racionais",
    Produção: "Produzem mel de alta qualidade, muito apreciado por seu sabor e aroma característicos. Além do mel, também produzem própolis e geleia real",
    tags: "Várias variedades Santa Catarina",
    link: "https://www.criarabelhas.com.br/abelhas-manduri/",
    imagem: "https://www.criarabelhas.com.br/wp-content/uploads/2018/08/Abelhas-Manduri-Preta-Melipona-Marginata.jpg.webp",
  },
  {
    nome: "Mirim (Plebeia sp.)",
    descricao: "A abelha mirim, pertencente ao gênero Plebeia, é uma espécie pequena e dócil, bastante popular entre os meliponicultores iniciantes. Existem diversas espécies de mirim, cada uma com suas características particulares, mas todas compartilham algumas características em comum.",
    ocorrencia: "Região Sul",
    Tamanho: "Muito pequenas, com cerca de 3 a 4 mm de comprimento, sendo uma das menores abelhas sem ferrão",
    Coloração: "Geralmente escura, com algumas variações de tonalidade e, em algumas espécies, pequenas manchas amarelas na cabeça.",
    Ninhos: "Constroem seus ninhos em cavidades de árvores, paredes ou outros locais protegidos. Os ninhos são menores em comparação com outras espécies de abelhas sem ferrão.",
    Produção: "Produzem mel em pequenas quantidades, mas de alta qualidade. O mel de mirim é considerado um dos mais saborosos entre os meles de abelhas sem ferrão. Além do mel, também produzem própolis e geleia real.",
    tags: "Pequeno porte Dócil Plebeia",
    link: "https://pt.wikipedia.org/wiki/Abelha-mirim",
    imagem: "https://abelha.org.br/wp-content/uploads/2022/02/Plebeia-droryana.jpg",
  },
  {
    nome: "Canudo (Scaptotrigona sp.)",
    descricao:
      "A abelha canudo, cientificamente conhecida como Scaptotrigona depilis, é uma espécie de abelha social sem ferrão bastante comum em diversas regiões do Brasil. Seu nome popular se deve ao fato de construir ninhos com entrada em forma de canudo, uma característica marcante dessa espécie.",
    ocorrencia: "Região Sul",
    tamnaho: "Pequena, com cerca de 4 a 5 mm de comprimento.",
    Coloração: "Predominantemente preta, com algumas variações de tonalidade.",
    Ninhos: "Constroem seus ninhos em cavidades de árvores, paredes ou outros locais protegidos. A entrada do ninho, em forma de canudo, é construída com cerume (mistura de cera e própolis).",
    Produção: "São excelentes produtoras de mel, que é considerado de alta qualidade e possui propriedades medicinais. Além do mel, também produzem própolis e geleia real.",
    tags: "Ninho em forma de canudo Scaptotrigona",
    link: "https://pt.wikipedia.org/wiki/Scaptotrigona_depilis",
    imagem: "https://exemplo.com/imagem_canudo.jpg",
  },
];
